const pairs = [
['Zurück zur Startseite','Back to homepage'],['Zum Inhalt springen','Skip to content'],['Streetwear · Auf Anfrage','Streetwear · By request'],['Luxurious Collection · Auf Anfrage','Luxury collection · By request'],
['Anders geschnitten. Für dich gemacht.','Cut different. Made yours.'],['Progressive Silhouetten und präzise Details – im Atelier als Einzelstück für dich entwickelt.','Progressive silhouettes and precise details—developed in the atelier as a one-off piece for you.'],['Leiser Luxus. Einzigartig Ihrer.','Quiet luxury. Uniquely yours.'],['Skulpturale Formen, präzise Linien und ein Finish, das ausschließlich für Sie entsteht.','Sculptural forms, precise lines, and a finish created exclusively for you.'],
['Dein Piece anfragen','Request your piece'],['Private Anfrage starten','Start a private inquiry'],['Drop entdecken','Discover the drop'],['Die Edition entdecken','Discover the edition'],['Auf Anfrage gefertigt · Keine Massenproduktion · Deine Regeln','Made on request · No mass production · Your rules'],['Auf Anfrage gefertigt · Persönlich kuratiert · Einzeln gefertigt','Made on request · Personally curated · Individually crafted'],
['Unser Anspruch','Our approach'],['01 / Silhouette','01 / Silhouette'],['01 / Form','01 / Form'],['02 / Identität','02 / Identity'],['02 / Dialog','02 / Dialogue'],['03 / Fertigung','03 / Craft'],['03 / Atelier','03 / Atelier'],['Progressiv','Progressive'],['Skulptural','Sculptural'],['Persönlich','Personal'],['Limitiert','Limited'],['Einzigartig','Unique'],
['Klare Volumen und grafische Linien für eine unverwechselbare Präsenz.','Strong volumes and graphic lines create an unmistakable presence.'],['Farbe, Proportion und Finish entstehen im direkten Dialog mit dir.','Color, proportion, and finish emerge through a direct dialogue with you.'],['Auf Anfrage im Atelier gefertigt – niemals anonymer Massenstandard.','Made to request in the atelier—never anonymous mass production.'],['Ruhige Linien und ausgewählte Materialien mit bleibender Wirkung.','Quiet lines and selected materials with lasting impact.'],['Proportion, Farbe und Finish werden exklusiv für Sie komponiert.','Proportion, color, and finish are composed exclusively for you.'],['Einzeln auf Anfrage gefertigt – bewusst jenseits der Serie.','Individually made to request—deliberately beyond serial production.'],
['Kollektion','Collection'],['Aktueller Drop','Current drop'],['Die private Edition','The private edition'],['Alle','All'],['Hosen','Trousers'],['Oberteile','Tops'],['Accessoires','Accessories'],['Handtaschen','Handbags'],['Bespoke-Hosen','Bespoke trousers'],['Bespoke','Bespoke'],['Dein Piece. Dein Ausdruck.','Your piece. Your expression.'],['Eine Signatur, nur für Sie.','A signature made only for you.'],
['Bestehendes Design anfragen','Request an existing design'],['Sie wählen einen Entwurf aus der Kollektion. Details, Machbarkeit und Umfang werden persönlich abgestimmt.','Choose a collection design. Details, feasibility, and scope are agreed personally.'],['Zur Kollektion','View the collection'],['Individuelles Design entwickeln','Develop a custom design'],['Sie beschreiben Richtung, Anlass und Wünsche. Daraus entsteht ein abgestimmter Entwurfsprozess.','Share your direction, occasion, and wishes. We turn them into a tailored design process.'],['Individuelles Design anfragen','Request a custom design'],
['Ablauf','Process'],['Von der Idee auf die Straße','From idea to street'],['Vom ersten Gedanken zum Signature Piece','From first thought to signature piece'],['Anfrage und Designrichtung','Inquiry and design direction'],['Erste Einordnung von Kategorie, Stil und Rahmen.','We establish category, style, and scope.'],['Persönliche Abstimmung','Personal consultation'],['Details werden vor Fertigungsbeginn geklärt.','Every detail is clarified before production.'],['Entwurf und Freigabe','Design and approval'],['Umfang, Machbarkeit und Preis werden individuell bestätigt.','Scope, feasibility, and price are confirmed individually.'],['Fertigung auf Anfrage','Made to request'],['Keine Lagerware, kein standardisierter Checkout.','No stock goods and no standardized checkout.'],
['Atelier','Atelier'],['Entworfen für Präsenz, nicht für den Mainstream.','Designed for presence, not the mainstream.'],['Persönlichkeit ist der seltenste Luxus.','Personality is the rarest luxury.'],['Bernd Wagner Designs übersetzt Subkultur, Bewegung und Persönlichkeit in tragbare Statements. Jedes Piece wird auf Anfrage abgestimmt und für seinen eigenen Auftritt geschaffen.','Bernd Wagner Designs translates subculture, movement, and personality into wearable statements. Every piece is tailored to request and created for its own presence.'],['Im Atelier treffen klare Linien auf individuelle Wünsche. So entstehen Taschen und Hosen mit Haltung – persönlich abgestimmt und ausschließlich auf Anfrage gefertigt.','In the atelier, clean lines meet individual wishes. Bags and trousers with character emerge—personally tailored and made only to request.'],
['Häufige Fragen','Frequently asked questions'],['Anfrage','Inquiry'],['Design anfragen','Request a design'],['Bitte senden Sie keine sensiblen Maßdaten im Erstkontakt. Eine Zusammenfassung wird vor dem Versand angezeigt.','Please do not send sensitive measurements in your first message. A summary is shown before sending.'],['Vor- und Nachname *','Full name *'],['E-Mail-Adresse *','Email address *'],['Telefonnummer','Phone number'],['Anfrage-Typ','Inquiry type'],['Noch offen','Not decided'],['Gewünschtes Design','Preferred design'],['Noch offen / nicht relevant','Not decided / not applicable'],['Farb-, Material- oder Printwünsche','Color, material, or print wishes'],['Anlass oder Zeitrahmen','Occasion or timeline'],['Budgetrahmen','Budget range'],['Nachricht *','Message *'],['Anfrage vorbereiten','Prepare inquiry'],['Zusammenfassung kopieren','Copy summary'],['E-Mail-Fallback','Email fallback'],['Impressum','Legal notice'],['Datenschutzerklärung','Privacy policy']
];
const normalized = new Map();
for (const [de,en] of pairs) { normalized.set(de,{de,en}); normalized.set(en,{de,en}); }
function applyLanguage(lang) {
 document.documentElement.lang=lang==='en'?'en':'de';
 document.querySelectorAll('body *').forEach(el=>{
  if (['SCRIPT','STYLE'].includes(el.tagName)) return;
  [...el.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).forEach(node=>{
   const raw=node.nodeValue, value=raw.trim(), entry=normalized.get(value); if(!entry)return;
   node.nodeValue=raw.replace(value,entry[lang]);
  });
 });
 document.querySelector('[data-lang-de]')?.classList.toggle('active',lang==='de');
 document.querySelector('[data-lang-en]')?.classList.toggle('active',lang==='en');
 document.querySelector('[data-language-toggle]')?.setAttribute('aria-label',lang==='de'?'Switch to English':'Zur deutschen Sprache wechseln');
 localStorage.setItem('bwd-language',lang);
}
export function initLanguage(){
 let lang=localStorage.getItem('bwd-language')||'de'; applyLanguage(lang);
 document.querySelector('[data-language-toggle]')?.addEventListener('click',()=>{lang=lang==='de'?'en':'de';applyLanguage(lang)});
 new MutationObserver(()=>applyLanguage(lang)).observe(document.body,{childList:true,subtree:true});
}
